CREATE TABLE "ArticleType" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(60) NOT NULL, "Image" varchar(512) NULL,
  "Meun" smallint NOT NULL DEFAULT 0 CONSTRAINT "CK_ArticleType_Meun" CHECK ("Meun" >= 0),
  "Version" bigint NOT NULL DEFAULT 1 CONSTRAINT "CK_ArticleType_Version" CHECK ("Version" > 0),
  "CreationTime" timestamptz NOT NULL DEFAULT now(), "LastModificationTime" timestamptz NULL,
  "DeletionTime" timestamptz NULL, "IsDeleted" boolean NOT NULL DEFAULT false,
  CONSTRAINT "CK_ArticleType_DeletionState" CHECK (("IsDeleted" = false AND "DeletionTime" IS NULL) OR ("IsDeleted" = true AND "DeletionTime" IS NOT NULL))
);
CREATE UNIQUE INDEX "UX_ArticleType_Name_Active" ON "ArticleType" ("Name") WHERE "IsDeleted" = false;
CREATE TABLE "Tag" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" varchar(60) NOT NULL,
  "Version" bigint NOT NULL DEFAULT 1 CONSTRAINT "CK_Tag_Version" CHECK ("Version" > 0),
  "CreationTime" timestamptz NOT NULL DEFAULT now(), "LastModificationTime" timestamptz NULL,
  "DeletionTime" timestamptz NULL, "IsDeleted" boolean NOT NULL DEFAULT false,
  CONSTRAINT "CK_Tag_DeletionState" CHECK (("IsDeleted" = false AND "DeletionTime" IS NULL) OR ("IsDeleted" = true AND "DeletionTime" IS NOT NULL))
);
CREATE UNIQUE INDEX "UX_Tag_Name_Active" ON "Tag" ("Name") WHERE "IsDeleted" = false;
CREATE TABLE "Article" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ArticleTypeId" bigint NOT NULL, "Title" varchar(120) NOT NULL, "Slug" varchar(160) NOT NULL,
  "Digest" varchar(500) NOT NULL, "Content" text NOT NULL,
  "Status" smallint NOT NULL DEFAULT 1 CONSTRAINT "CK_Article_Status" CHECK ("Status" IN (1,2,3)),
  "Support" bigint NOT NULL DEFAULT 0 CONSTRAINT "CK_Article_Support" CHECK ("Support" >= 0),
  "Comment" bigint NOT NULL DEFAULT 0 CONSTRAINT "CK_Article_Comment" CHECK ("Comment" >= 0),
  "Visited" bigint NOT NULL DEFAULT 0 CONSTRAINT "CK_Article_Visited" CHECK ("Visited" >= 0),
  "Version" bigint NOT NULL DEFAULT 1 CONSTRAINT "CK_Article_Version" CHECK ("Version" > 0),
  "CreationTime" timestamptz NOT NULL DEFAULT now(), "LastModificationTime" timestamptz NULL,
  "DeletionTime" timestamptz NULL, "IsDeleted" boolean NOT NULL DEFAULT false,
  CONSTRAINT "CK_Article_DeletionState" CHECK (("IsDeleted" = false AND "DeletionTime" IS NULL) OR ("IsDeleted" = true AND "DeletionTime" IS NOT NULL)),
  CONSTRAINT "FK_Article_ArticleType" FOREIGN KEY ("ArticleTypeId") REFERENCES "ArticleType" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX "UX_Article_Slug_Active" ON "Article" ("Slug") WHERE "IsDeleted" = false;
CREATE UNIQUE INDEX "UX_Article_Title_Active" ON "Article" ("Title") WHERE "IsDeleted" = false;
CREATE INDEX "IX_Article_ArticleTypeId" ON "Article" ("ArticleTypeId");
CREATE INDEX "IX_Article_Status_CreationTime" ON "Article" ("Status", "CreationTime" DESC);
CREATE TABLE "TagArticle" (
  "ArticleId" bigint NOT NULL, "TagId" bigint NOT NULL,
  CONSTRAINT "PK_TagArticle" PRIMARY KEY ("ArticleId", "TagId"),
  CONSTRAINT "FK_TagArticle_Article" FOREIGN KEY ("ArticleId") REFERENCES "Article" ("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_TagArticle_Tag" FOREIGN KEY ("TagId") REFERENCES "Tag" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_TagArticle_TagId" ON "TagArticle" ("TagId");
