CREATE TABLE article_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(60) NOT NULL,
  image varchar(512) NULL,
  meun smallint NOT NULL DEFAULT 0 CONSTRAINT article_types_meun_check CHECK (meun >= 0),
  version bigint NOT NULL DEFAULT 1 CONSTRAINT article_types_version_check CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NULL,
  deleted_at timestamptz NULL,
  is_deleted boolean NOT NULL DEFAULT false,
  CONSTRAINT article_types_deletion_state_check CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
);
CREATE UNIQUE INDEX article_types_name_active_idx ON article_types (name) WHERE is_deleted = false;

CREATE TABLE tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(60) NOT NULL,
  version bigint NOT NULL DEFAULT 1 CONSTRAINT tags_version_check CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NULL,
  deleted_at timestamptz NULL,
  is_deleted boolean NOT NULL DEFAULT false,
  CONSTRAINT tags_deletion_state_check CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL))
);
CREATE UNIQUE INDEX tags_name_active_idx ON tags (name) WHERE is_deleted = false;

CREATE TABLE articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_type_id bigint NOT NULL,
  title varchar(120) NOT NULL,
  slug varchar(160) NOT NULL,
  digest varchar(500) NOT NULL,
  content text NOT NULL,
  status smallint NOT NULL DEFAULT 1 CONSTRAINT articles_status_check CHECK (status IN (1, 2, 3)),
  support bigint NOT NULL DEFAULT 0 CONSTRAINT articles_support_check CHECK (support >= 0),
  comment bigint NOT NULL DEFAULT 0 CONSTRAINT articles_comment_check CHECK (comment >= 0),
  visited bigint NOT NULL DEFAULT 0 CONSTRAINT articles_visited_check CHECK (visited >= 0),
  version bigint NOT NULL DEFAULT 1 CONSTRAINT articles_version_check CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NULL,
  deleted_at timestamptz NULL,
  is_deleted boolean NOT NULL DEFAULT false,
  CONSTRAINT articles_deletion_state_check CHECK ((is_deleted = false AND deleted_at IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL)),
  CONSTRAINT articles_article_type_id_fkey FOREIGN KEY (article_type_id) REFERENCES article_types (id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX articles_slug_active_idx ON articles (slug) WHERE is_deleted = false;
CREATE UNIQUE INDEX articles_title_active_idx ON articles (title) WHERE is_deleted = false;
CREATE INDEX articles_article_type_id_idx ON articles (article_type_id);
CREATE INDEX articles_status_created_at_idx ON articles (status, created_at DESC);

CREATE TABLE article_tags (
  article_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  CONSTRAINT article_tags_pkey PRIMARY KEY (article_id, tag_id),
  CONSTRAINT article_tags_article_id_fkey FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE,
  CONSTRAINT article_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE RESTRICT
);
CREATE INDEX article_tags_tag_id_idx ON article_tags (tag_id);
