package migrations

import (
	"io/fs"
	"strings"
	"testing"
)

func Test_InitialMigration_preserves_article_bigint_contract(t *testing.T) {
	source, err := fs.ReadFile(Files(), "000001_initial.up.sql")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(source), `id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`) {
		t.Fatal("000001 必须保持文章 bigint 主键契约")
	}
}

func Test_ArticleImageMigration_contains_required_schema_contract(t *testing.T) {
	source, err := fs.ReadFile(Files(), "000002_article_images.up.sql")
	if err != nil {
		t.Fatal(err)
	}
	sql := string(source)
	required := []string{"article_images", "article_image_references", "VARCHAR(32)", "BIGINT", "pending", "committed", "orphaned", "ON DELETE CASCADE", "article_image_references_image_id_idx", "width::bigint * height::bigint <= 25000000"}
	for _, fragment := range required {
		if !strings.Contains(sql, fragment) {
			t.Fatalf("迁移缺少 %q", fragment)
		}
	}
	if CurrentVersion != 5 {
		t.Fatalf("期望迁移版本 5，实际 %d", CurrentVersion)
	}
}

func Test_ArticleImageCleanupClaimMigration_contains_claim_contract(t *testing.T) {
	source, err := fs.ReadFile(Files(), "000003_article_image_cleanup_claims.up.sql")
	if err != nil {
		t.Fatal(err)
	}
	sql := string(source)
	for _, fragment := range []string{"cleanup_claim_token", "cleanup_claim_expires_at", "article_images_cleanup_claim_check", "article_images_cleanup_claim_idx"} {
		if !strings.Contains(sql, fragment) {
			t.Fatalf("清理领取迁移缺少 %q", fragment)
		}
	}
}

func Test_UserMigration_contains_default_account_contract(t *testing.T) {
	source, err := fs.ReadFile(Files(), "000004_users.up.sql")
	if err != nil {
		t.Fatal(err)
	}
	sql := string(source)
	for _, fragment := range []string{
		"CREATE TABLE users",
		"id varchar(32)",
		"users_id_check",
		"username varchar(64)",
		"password_hash varchar(255)",
		"users_username_check",
		"users_password_hash_check",
		"users_username_idx",
		"00000000000000000000000000000001",
		"admin",
		"$2a$10$RLOUsCJG.Ntj2lqIfL9JbuXrJjrifIl45KecRH8fQZ3pHDOgFYIva",
		"ON CONFLICT (username) DO NOTHING",
	} {
		if !strings.Contains(sql, fragment) {
			t.Fatalf("用户迁移缺少 %q", fragment)
		}
	}
	if CurrentVersion != 5 {
		t.Fatalf("期望迁移版本 5，实际 %d", CurrentVersion)
	}

	down, err := fs.ReadFile(Files(), "000004_users.down.sql")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(down), "DROP TABLE users") {
		t.Fatal("用户回滚迁移必须删除 users 表")
	}
}
