package migrations

import (
	"io/fs"
	"strings"
	"testing"
)

func Test_InitialMigration_preserves_article_bigint_contract(t *testing.T) {
	source, err := fs.ReadFile(Files(), "000001_initial.up.sql")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(source), `"Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`) {
		t.Fatal("000001 必须保持文章 bigint 主键契约")
	}
}

func Test_ArticleImageMigration_contains_required_schema_contract(t *testing.T) {
	source, err := fs.ReadFile(Files(), "000002_article_images.up.sql")
	if err != nil {
		t.Fatal(err)
	}
	sql := string(source)
	required := []string{"article_images", "article_image_references", "VARCHAR(32)", "BIGINT", "pending", "committed", "orphaned", "ON DELETE CASCADE", "article_image_references_image_id_idx", "width::bigint * height::bigint <= 25000000"}
	for _, fragment := range required {
		if !strings.Contains(sql, fragment) {
			t.Fatalf("迁移缺少 %q", fragment)
		}
	}
	if CurrentVersion != 2 {
		t.Fatalf("期望迁移版本 2，实际 %d", CurrentVersion)
	}
}
