package main

import (
	"container/heap"
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"runtime/debug"
	"sort"
	"strings"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"

	"github.com/PengYuee/SCYG.Blog/backend/internal/modules/content/article"
	"github.com/PengYuee/SCYG.Blog/backend/internal/modules/content/image"
)

type articleRow struct {
	ID      int64
	Content string
}
type imageRow struct {
	ID, StorageKey, Status, SHA256 string
	ByteSize                       int64
	CreatedAt, ExpiresAt           time.Time
	CommittedAt, OrphanedAt        *time.Time
}
type referenceRow struct {
	ArticleID int64
	ImageID   string
}
type finding struct {
	Category   string `json:"category"`
	ArticleID  string `json:"articleId,omitempty"`
	ImageID    string `json:"imageId,omitempty"`
	StorageKey string `json:"storageKey,omitempty"`
	Detail     string `json:"detail"`
}
type tempCandidate struct {
	Name       string    `json:"name"`
	ModifiedAt time.Time `json:"modifiedAt"`
}
type reconciliationReport struct {
	GeneratedAt             time.Time       `json:"generatedAt"`
	ArticlesChecked         int             `json:"articlesChecked"`
	ImagesChecked           int             `json:"imagesChecked"`
	ReferencesChecked       int             `json:"referencesChecked"`
	BlockingInconsistencies []finding       `json:"blockingInconsistencies"`
	PendingCandidates       []string        `json:"pendingCandidates"`
	OrphanedCandidates      []string        `json:"orphanedCandidates"`
	TemporaryFileCandidates []tempCandidate `json:"temporaryFileCandidates"`
	TemporaryFilesTruncated bool            `json:"temporaryFilesTruncated"`
	SnapshotStartedAt       time.Time       `json:"snapshotStartedAt"`
}
type manifest struct {
	AttemptID         string            `json:"attemptId"`
	PreviousAttempt   string            `json:"previousAttempt,omitempty"`
	CommandVersion    string            `json:"commandVersion"`
	Release           string            `json:"release"`
	Phase             string            `json:"phase"`
	Environment       string            `json:"environment"`
	EvidenceID        string            `json:"evidenceId"`
	EvidenceSHA256    string            `json:"evidenceSha256"`
	StartedAt         time.Time         `json:"startedAt"`
	SnapshotStartedAt time.Time         `json:"snapshotStartedAt"`
	FinishedAt        time.Time         `json:"finishedAt"`
	ExitCode          int               `json:"exitCode"`
	ArticlesChecked   int               `json:"articlesChecked"`
	ImagesChecked     int               `json:"imagesChecked"`
	ReferencesChecked int               `json:"referencesChecked"`
	BlockingCount     int               `json:"blockingCount"`
	CandidateCount    int               `json:"candidateCount"`
	Truncated         bool              `json:"temporaryFilesTruncated"`
	ResultSHA256      map[string]string `json:"resultSha256"`
}

func execute(options commandOptions) error {
	config, err := loadReconcileConfig(options.configPath)
	if err != nil {
		return err
	}
	evidenceBytes, evidence, err := loadAndValidateEvidence(options.evidencePath, options, config)
	if err != nil {
		return err
	}
	if options.previousAttempt != "" {
		if !safeSegment.MatchString(options.previousAttempt) {
			return errors.New("previous-attempt is unsafe")
		}
		previous := filepath.Join(options.evidenceRoot, options.release, "reconciliation", options.phase, options.previousAttempt)
		if err := validatePreviousAttempt(previous, options, evidence); err != nil {
			return err
		}
	}
	tempDir, finalDir, err := prepareAttemptRoot(options)
	if err != nil {
		return err
	}
	//nolint:gosec // tempDir is generated by prepareAttemptRoot inside the configured evidence root.
	defer func() { _ = os.RemoveAll(tempDir) }()
	if err := reserveEvidenceID(filepath.Dir(finalDir), filepath.Base(finalDir), evidence.EvidenceID); err != nil {
		return err
	}
	started := time.Now().UTC()
	root, err := filepath.Abs(filepath.Clean(config.ArticleImages.Directory))
	if err != nil {
		return err
	}
	if err = ensureNoSymlink(root); err != nil {
		return err
	}
	ctx, cancel := context.WithDeadline(context.Background(), evidence.WindowExpiresAt)
	defer cancel()
	report, checkErr := runReconciliation(ctx, config.Database.DSN, root, config.ArticleImages.PendingTTL, config.Reconcile.TempScanLimit)
	if deadlineErr := ctx.Err(); deadlineErr != nil {
		checkErr = errors.Join(checkErr, fmt.Errorf("quiet window expired during reconciliation: %w", deadlineErr))
	}
	finished := time.Now().UTC()
	if writeErr := writeAttempt(tempDir, evidenceBytes, evidence, options, report, started, finished, checkErr); writeErr != nil {
		return writeErr
	}
	//nolint:gosec // tempDir and finalDir are generated inside the validated evidence root.
	if err = os.Rename(tempDir, finalDir); err != nil {
		return fmt.Errorf("publish reconciliation attempt: %w", err)
	}
	if checkErr != nil {
		return checkErr
	}
	if len(report.BlockingInconsistencies) > 0 {
		return &exitError{code: 1, msg: fmt.Sprintf("reconciliation found %d blocking inconsistencies; see %s", len(report.BlockingInconsistencies), finalDir)}
	}
	fmt.Printf("reconciliation succeeded: %s\n", finalDir)
	return nil
}

func runReconciliation(ctx context.Context, dsn, root string, pendingTTL time.Duration, tempLimit int) (reconciliationReport, error) {
	report := reconciliationReport{GeneratedAt: time.Now().UTC(), BlockingInconsistencies: []finding{}}
	blobRoot, err := os.OpenRoot(root)
	if err != nil {
		return report, fmt.Errorf("open reconciliation Blob root: %w", err)
	}
	defer func() { _ = blobRoot.Close() }()
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return report, fmt.Errorf("open reconciliation database: %w", err)
	}
	defer func() { _ = db.Close() }()
	if err = db.PingContext(ctx); err != nil {
		return report, fmt.Errorf("ping reconciliation database: %w", err)
	}
	tx, err := db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelRepeatableRead, ReadOnly: true})
	if err != nil {
		return report, fmt.Errorf("begin read-only snapshot: %w", err)
	}
	report.SnapshotStartedAt = time.Now().UTC()
	defer func() { _ = tx.Rollback() }()
	articles, err := loadArticles(ctx, tx)
	if err != nil {
		return report, err
	}
	images, err := loadImages(ctx, tx)
	if err != nil {
		return report, err
	}
	references, err := loadReferences(ctx, tx)
	if err != nil {
		return report, err
	}
	report.ArticlesChecked, report.ImagesChecked, report.ReferencesChecked = len(articles), len(images), len(references)
	refsByArticle := make(map[int64]map[string]struct{})
	refsByImage := make(map[string]int)
	for _, ref := range references {
		if refsByArticle[ref.ArticleID] == nil {
			refsByArticle[ref.ArticleID] = map[string]struct{}{}
		}
		refsByArticle[ref.ArticleID][ref.ImageID] = struct{}{}
		refsByImage[ref.ImageID]++
		if _, ok := images[ref.ImageID]; !ok {
			report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "reference", ArticleID: redactValue(fmt.Sprint(ref.ArticleID)), ImageID: redactValue(ref.ImageID), Detail: "reference points to missing image"})
		}
	}
	for _, articleRow := range articles {
		keys, parseErr := article.ManagedImageReferences(articleRow.Content)
		if parseErr != nil {
			report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "markdown", ArticleID: redactValue(fmt.Sprint(articleRow.ID)), Detail: "controlled image reference is invalid"})
			continue
		}
		if _, parseErr = image.ParseReferenceKeys(keys); parseErr != nil {
			report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "markdown", ArticleID: redactValue(fmt.Sprint(articleRow.ID)), Detail: "image storage key is invalid"})
			continue
		}
		expected := map[string]struct{}{}
		for _, key := range keys {
			row, ok := imageByStorageKey(images, key)
			if !ok {
				report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "reference", ArticleID: redactValue(fmt.Sprint(articleRow.ID)), StorageKey: redactValue(key), Detail: "markdown references missing image metadata"})
				continue
			}
			expected[row.ID] = struct{}{}
		}
		if !sameSet(expected, refsByArticle[articleRow.ID]) {
			report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "reference", ArticleID: redactValue(fmt.Sprint(articleRow.ID)), Detail: "markdown image set differs from relation set"})
		}
	}
	now := report.SnapshotStartedAt
	blobChecks := make([]imageRow, 0, len(images))
	for _, row := range images {
		count := refsByImage[row.ID]
		if !validImageTimestamps(row) {
			report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "image_state", ImageID: redactValue(row.ID), Detail: "image lifecycle timestamps are invalid"})
			continue
		}
		switch row.Status {
		case "pending":
			if count != 0 {
				report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "image_state", ImageID: redactValue(row.ID), Detail: "pending image has references"})
			}
			if !row.ExpiresAt.After(now) {
				if count == 0 {
					report.PendingCandidates = append(report.PendingCandidates, redactValue(row.ID))
				}
			} else {
				blobChecks = append(blobChecks, row)
			}
		case "committed":
			if count < 1 {
				report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "image_state", ImageID: redactValue(row.ID), Detail: "committed image has no references"})
			}
			blobChecks = append(blobChecks, row)
		case "orphaned":
			if count != 0 {
				report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "image_state", ImageID: redactValue(row.ID), Detail: "orphaned image has references"})
			}
			if !row.ExpiresAt.After(now) {
				if count == 0 {
					report.OrphanedCandidates = append(report.OrphanedCandidates, redactValue(row.ID))
				}
			} else {
				blobChecks = append(blobChecks, row)
			}
		default:
			report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "image_state", ImageID: redactValue(row.ID), Detail: "unknown image status"})
		}
	}
	candidates, truncated, err := listTempCandidates(ctx, blobRoot, now.Add(-pendingTTL), tempLimit)
	if err != nil {
		return report, err
	}
	report.TemporaryFileCandidates, report.TemporaryFilesTruncated = candidates, truncated
	for _, row := range blobChecks {
		if err := checkBlob(ctx, &report, blobRoot, row); err != nil {
			return report, err
		}
	}
	return report, nil
}

func validatePreviousAttempt(path string, options commandOptions, evidence quiesceEvidence) error {
	if err := ensureNoSymlink(path); err != nil {
		return err
	}
	info, err := os.Stat(path)
	if err != nil || !info.IsDir() {
		return errors.New("previous-attempt must identify an existing attempt directory")
	}
	previous, err := readManifest(path)
	if err != nil {
		return err
	}
	if previous.AttemptID == "" || previous.AttemptID != filepath.Base(path) || previous.Release != options.release || previous.Phase != options.phase || previous.EvidenceID == "" {
		return errors.New("previous-attempt manifest is incomplete or mismatched")
	}
	if previous.EvidenceID == evidence.EvidenceID {
		return errors.New("quiesce evidence id has already been used")
	}
	return nil
}

func readManifest(path string) (manifest, error) {
	manifestPath := filepath.Join(path, "manifest.json")
	if err := ensureNoSymlink(manifestPath); err != nil {
		return manifest{}, err
	}
	//nolint:gosec // manifestPath is derived from a validated previous attempt and checked for symlinks.
	manifestBytes, err := os.ReadFile(manifestPath)
	if err != nil {
		return manifest{}, fmt.Errorf("read previous attempt manifest: %w", err)
	}
	var value manifest
	if err := json.Unmarshal(manifestBytes, &value); err != nil {
		return manifest{}, fmt.Errorf("parse previous attempt manifest: %w", err)
	}
	return value, nil
}

func ensureEvidenceIDUnused(parent, currentAttempt, evidenceID string) error {
	entries, err := os.ReadDir(parent)
	if err != nil {
		return fmt.Errorf("read reconciliation attempts: %w", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() || entry.Name() == currentAttempt || !safeSegment.MatchString(entry.Name()) {
			continue
		}
		value, err := readManifest(filepath.Join(parent, entry.Name()))
		if err != nil {
			return err
		}
		if value.EvidenceID == evidenceID {
			return errors.New("quiesce evidence id has already been used")
		}
	}
	return nil
}

func reserveEvidenceID(parent, currentAttempt, evidenceID string) error {
	if err := ensureEvidenceIDUnused(parent, currentAttempt, evidenceID); err != nil {
		return err
	}
	reservationPath := filepath.Join(parent, ".evidence-"+evidenceHash([]byte(evidenceID))+".reservation")
	//nolint:gosec // reservationPath is a generated hash filename beneath the validated parent.
	file, err := os.OpenFile(reservationPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		if errors.Is(err, os.ErrExist) {
			return errors.New("quiesce evidence id has already been used")
		}
		return fmt.Errorf("reserve quiesce evidence id: %w", err)
	}
	if _, err = io.WriteString(file, evidenceHash([]byte(evidenceID))+"\n"); err != nil {
		_ = file.Close()
		return fmt.Errorf("write quiesce evidence reservation: %w", err)
	}
	if err = file.Close(); err != nil {
		return fmt.Errorf("close quiesce evidence reservation: %w", err)
	}
	return nil
}

func reconcileCommandVersion() string {
	const sourceVersion = "content-reconcile-v1"
	info, ok := debug.ReadBuildInfo()
	if !ok || info.Path == "" {
		return sourceVersion
	}
	var revision, dirty string
	for _, setting := range info.Settings {
		switch setting.Key {
		case "vcs.revision":
			revision = setting.Value
		case "vcs.modified":
			dirty = setting.Value
		}
	}
	if revision == "" {
		return sourceVersion
	}
	if dirty == "true" {
		revision += "-dirty"
	}
	return info.Path + "@" + revision
}

func loadArticles(ctx context.Context, tx *sql.Tx) ([]articleRow, error) {
	rows, err := tx.QueryContext(ctx, `SELECT id, content FROM articles`)
	if err != nil {
		return nil, fmt.Errorf("read articles: %w", err)
	}
	defer func() { _ = rows.Close() }()
	var result []articleRow
	for rows.Next() {
		var row articleRow
		if err := rows.Scan(&row.ID, &row.Content); err != nil {
			return nil, err
		}
		result = append(result, row)
	}
	return result, rows.Err()
}

func loadImages(ctx context.Context, tx *sql.Tx) (map[string]imageRow, error) {
	rows, err := tx.QueryContext(ctx, `SELECT id, storage_key, status, sha256, byte_size, created_at, committed_at, orphaned_at, expires_at FROM article_images`)
	if err != nil {
		return nil, fmt.Errorf("read images: %w", err)
	}
	defer func() { _ = rows.Close() }()
	result := map[string]imageRow{}
	for rows.Next() {
		var row imageRow
		var committedAt, orphanedAt sql.NullTime
		if err := rows.Scan(&row.ID, &row.StorageKey, &row.Status, &row.SHA256, &row.ByteSize, &row.CreatedAt, &committedAt, &orphanedAt, &row.ExpiresAt); err != nil {
			return nil, err
		}
		if committedAt.Valid {
			value := committedAt.Time.UTC()
			row.CommittedAt = &value
		}
		if orphanedAt.Valid {
			value := orphanedAt.Time.UTC()
			row.OrphanedAt = &value
		}
		result[row.ID] = row
	}
	return result, rows.Err()
}

func loadReferences(ctx context.Context, tx *sql.Tx) ([]referenceRow, error) {
	rows, err := tx.QueryContext(ctx, `SELECT article_id, image_id FROM article_image_references`)
	if err != nil {
		return nil, fmt.Errorf("read image references: %w", err)
	}
	defer func() { _ = rows.Close() }()
	var result []referenceRow
	for rows.Next() {
		var row referenceRow
		if err := rows.Scan(&row.ArticleID, &row.ImageID); err != nil {
			return nil, err
		}
		result = append(result, row)
	}
	return result, rows.Err()
}

func imageByStorageKey(images map[string]imageRow, key string) (imageRow, bool) {
	for _, row := range images {
		if row.StorageKey == key {
			return row, true
		}
	}
	return imageRow{}, false
}

type tempCandidateHeap []tempCandidate

func (candidates tempCandidateHeap) Len() int { return len(candidates) }
func (candidates tempCandidateHeap) Less(left, right int) bool {
	return tempCandidateBefore(candidates[right], candidates[left])
}

func (candidates tempCandidateHeap) Swap(left, right int) {
	candidates[left], candidates[right] = candidates[right], candidates[left]
}

func (candidates *tempCandidateHeap) Push(value any) {
	candidate, ok := value.(tempCandidate)
	if !ok {
		panic("reconciliation temp candidate heap received an invalid value")
	}
	*candidates = append(*candidates, candidate)
}

func (candidates *tempCandidateHeap) Pop() any {
	values := *candidates
	last := len(values) - 1
	value := values[last]
	*candidates = values[:last]
	return value
}

func tempCandidateBefore(left, right tempCandidate) bool {
	if left.ModifiedAt.Equal(right.ModifiedAt) {
		return left.Name < right.Name
	}
	return left.ModifiedAt.Before(right.ModifiedAt)
}

func listTempCandidates(ctx context.Context, root *os.Root, cutoff time.Time, limit int) ([]tempCandidate, bool, error) {
	if limit < 1 {
		return []tempCandidate{}, false, nil
	}
	directory, err := root.Open(".")
	if err != nil {
		return nil, false, err
	}
	defer func() { _ = directory.Close() }()
	candidates := tempCandidateHeap{}
	heap.Init(&candidates)
	truncated := false
	consider := func(entry fs.DirEntry) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		if !isReconciliationTempName(entry.Name()) || !entry.Type().IsRegular() {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		if info.ModTime().After(cutoff) {
			return nil
		}
		candidate := tempCandidate{Name: entry.Name(), ModifiedAt: info.ModTime().UTC()}
		if candidates.Len() < limit {
			heap.Push(&candidates, candidate)
			if candidates.Len() == limit {
				truncated = true
			}
			return nil
		}
		truncated = true
		if tempCandidateBefore(candidate, candidates[0]) {
			heap.Pop(&candidates)
			heap.Push(&candidates, candidate)
		}
		return nil
	}
	for {
		entries, readErr := directory.ReadDir(128)
		for _, entry := range entries {
			if err := consider(entry); err != nil {
				return nil, false, err
			}
		}
		if readErr != nil {
			if errors.Is(readErr, io.EOF) {
				break
			}
			return nil, false, readErr
		}
		if len(entries) == 0 {
			break
		}
	}
	result := make([]tempCandidate, candidates.Len())
	for index := len(result) - 1; index >= 0; index-- {
		value, ok := heap.Pop(&candidates).(tempCandidate)
		if !ok {
			return nil, false, errors.New("reconciliation temp candidate heap returned an invalid value")
		}
		result[index] = value
	}
	sort.Slice(result, func(left, right int) bool { return tempCandidateBefore(result[left], result[right]) })
	return result, truncated, nil
}

func validImageTimestamps(row imageRow) bool {
	created, expires := row.CreatedAt.UTC(), row.ExpiresAt.UTC()
	if created.IsZero() || !expires.After(created) {
		return false
	}
	committed := time.Time{}
	if row.CommittedAt != nil {
		committed = row.CommittedAt.UTC()
	}
	orphaned := time.Time{}
	if row.OrphanedAt != nil {
		orphaned = row.OrphanedAt.UTC()
	}
	switch row.Status {
	case "pending":
		return row.CommittedAt == nil && row.OrphanedAt == nil
	case "committed":
		return row.CommittedAt != nil && !committed.Before(created) && committed.Before(expires) && row.OrphanedAt == nil
	case "orphaned":
		return row.CommittedAt != nil && row.OrphanedAt != nil && !committed.Before(created) && !orphaned.Before(committed) && !expires.Before(orphaned)
	default:
		return true
	}
}

func isReconciliationTempName(name string) bool {
	if len(name) != len(".article-image-")+32+1+24+len(".tmp") || !strings.HasPrefix(name, ".article-image-") || !strings.HasSuffix(name, ".tmp") {
		return false
	}
	body := strings.TrimSuffix(strings.TrimPrefix(name, ".article-image-"), ".tmp")
	parts := strings.Split(body, "-")
	if len(parts) != 2 || len(parts[0]) != 32 || len(parts[1]) != 24 {
		return false
	}
	return isLowerHex(parts[0]) && isLowerHex(parts[1])
}

func isLowerHex(value string) bool {
	for _, char := range value {
		if (char < '0' || char > '9') && (char < 'a' || char > 'f') {
			return false
		}
	}
	return true
}

func sameSet(left, right map[string]struct{}) bool {
	if len(left) != len(right) {
		return false
	}
	for value := range left {
		if _, ok := right[value]; !ok {
			return false
		}
	}
	return true
}

func checkBlob(ctx context.Context, report *reconciliationReport, root *os.Root, row imageRow) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if _, err := image.NewStorageKey(row.StorageKey); err != nil {
		report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "blob", ImageID: redactValue(row.ID), StorageKey: redactValue(row.StorageKey), Detail: "unsafe storage key"})
		return nil
	}
	file, err := root.Open(row.StorageKey)
	if err != nil {
		report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "blob", ImageID: redactValue(row.ID), StorageKey: redactValue(row.StorageKey), Detail: "final blob is not readable"})
		return nil
	}
	defer func() { _ = file.Close() }()
	info, err := file.Stat()
	if err != nil || !info.Mode().IsRegular() {
		report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "blob", ImageID: redactValue(row.ID), StorageKey: redactValue(row.StorageKey), Detail: "final blob is not a regular file"})
		return nil
	}
	digest := sha256.New()
	size, copyErr := io.Copy(digest, contextReader{ctx: ctx, reader: file})
	if copyErr != nil {
		if ctxErr := ctx.Err(); ctxErr != nil {
			return ctxErr
		}
		report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "blob", ImageID: redactValue(row.ID), StorageKey: redactValue(row.StorageKey), Detail: "final blob could not be read"})
		return nil
	}
	if size != row.ByteSize || hex.EncodeToString(digest.Sum(nil)) != row.SHA256 {
		report.BlockingInconsistencies = append(report.BlockingInconsistencies, finding{Category: "blob", ImageID: redactValue(row.ID), StorageKey: redactValue(row.StorageKey), Detail: "final blob does not match metadata"})
	}
	return nil
}

type contextReader struct {
	ctx    context.Context
	reader io.Reader
}

func (reader contextReader) Read(buffer []byte) (int, error) {
	if err := reader.ctx.Err(); err != nil {
		return 0, err
	}
	return reader.reader.Read(buffer)
}

func writeAttempt(tempDir string, evidenceBytes []byte, evidence quiesceEvidence, options commandOptions, report reconciliationReport, started, finished time.Time, checkErr error) error {
	//nolint:gosec // writeAttempt writes fixed artifact names into its generated temporary directory.
	if err := os.WriteFile(filepath.Join(tempDir, "quiesce-evidence.json"), evidenceBytes, 0o600); err != nil {
		return err
	}
	reportBytes, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return err
	}
	reportBytes = append(reportBytes, '\n')
	//nolint:gosec // writeAttempt writes fixed artifact names into its generated temporary directory.
	if err = os.WriteFile(filepath.Join(tempDir, "report.json"), reportBytes, 0o600); err != nil {
		return err
	}
	exitCode := 0
	if len(report.BlockingInconsistencies) > 0 {
		exitCode = 1
	}
	if checkErr != nil {
		exitCode = 2
	}
	attempt := filepath.Base(tempDir)
	attempt = strings.SplitN(attempt, ".tmp-", 2)[0]
	candidateCount := len(report.PendingCandidates) + len(report.OrphanedCandidates) + len(report.TemporaryFileCandidates)
	m := manifest{AttemptID: attempt, PreviousAttempt: options.previousAttempt, CommandVersion: reconcileCommandVersion(), Release: options.release, Phase: options.phase, Environment: evidence.Environment, EvidenceID: evidence.EvidenceID, EvidenceSHA256: evidenceHash(evidenceBytes), StartedAt: started, SnapshotStartedAt: report.SnapshotStartedAt, FinishedAt: finished, ExitCode: exitCode, ArticlesChecked: report.ArticlesChecked, ImagesChecked: report.ImagesChecked, ReferencesChecked: report.ReferencesChecked, BlockingCount: len(report.BlockingInconsistencies), CandidateCount: candidateCount, Truncated: report.TemporaryFilesTruncated, ResultSHA256: map[string]string{"report.json": evidenceHash(reportBytes), "quiesce-evidence.json": evidenceHash(evidenceBytes)}}
	manifestBytes, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	manifestBytes = append(manifestBytes, '\n')
	//nolint:gosec // writeAttempt writes a fixed artifact into its generated temporary directory.
	return os.WriteFile(filepath.Join(tempDir, "manifest.json"), manifestBytes, 0o600)
}
