"""BlogContent client contracts; production Recipe tools remain read-only."""

from .client import BlogGrpcClient
from .contracts import (
    ArchiveArticle,
    ArticleId,
    ArticleResult,
    ArticleSucceeded,
    ArticleTypesSucceeded,
    BlogCommand,
    BlogFailure,
    BlogResult,
    BlogUserId,
    CorrelationId,
    CreateArticle,
    FailureKind,
    GetArticle,
    ListArticleTypes,
    ListTags,
    PublishArticle,
    RequestId,
    RequestIdentity,
    RpcDispatch,
    SearchArticles,
    SearchSucceeded,
    TagId,
    TagsSucceeded,
    TaxonomyResult,
    UpdateArticle,
)
from .security import InvalidDeadlineError

__all__ = [
    "ArchiveArticle",
    "ArticleId",
    "ArticleResult",
    "ArticleSucceeded",
    "ArticleTypesSucceeded",
    "BlogCommand",
    "BlogFailure",
    "BlogGrpcClient",
    "BlogResult",
    "BlogUserId",
    "CorrelationId",
    "CreateArticle",
    "FailureKind",
    "GetArticle",
    "InvalidDeadlineError",
    "ListArticleTypes",
    "ListTags",
    "PublishArticle",
    "RequestId",
    "RequestIdentity",
    "RpcDispatch",
    "SearchArticles",
    "SearchSucceeded",
    "TagId",
    "TagsSucceeded",
    "TaxonomyResult",
    "UpdateArticle",
]
