package architecture

import (
	"os"
	"path/filepath"
	"testing"
)

func Test_Architecture_ClassifiesGeneratedInitialization(t *testing.T) {
	cases := []struct {
		name, path, source string
		wantInit           bool
	}{
		{"generated marker", "bindings.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage fixture\nfunc init() {}", false},
		{"generated path is handwritten", "internal/generated/proto/bindings.go", "package fixture\nfunc init() {}", true},
		{"generated filename is handwritten", "api_generated.go", "package fixture\nfunc init() {}", true},
		{"informal marker is handwritten", "bindings.go", "// generated by a helper\npackage fixture\nfunc init() {}", true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			violations := scanClassificationFixture(t, tc.path, tc.source)
			if got := containsViolation(violations, "ARCH_INIT_SIDE_EFFECT", tc.path); got != tc.wantInit {
				t.Fatalf("init classification = %v, want %v: %v", got, tc.wantInit, violations)
			}
		})
	}
}

func Test_Architecture_ExternalHarnessDoesNotRelaxProductionLayers(t *testing.T) {
	imports := `import (
 _ "google.golang.org/grpc"
 _ "github.com/PengYuee/SCYG.Blog/backend/internal/generated/proto/scyg/blog/v1"
 _ "github.com/PengYuee/SCYG.Blog/backend/internal/platform/database"
 _ "github.com/PengYuee/SCYG.Blog/backend/internal/modules/identity/user"
)`
	cases := []struct {
		name, path, pkg string
		wantAllowed     bool
	}{
		{"external application harness", "internal/modules/content/application/harness_test.go", "application_test", true},
		{"same package application test", "internal/modules/content/application/harness_test.go", "application", false},
		{"production application", "internal/modules/content/application/harness.go", "application", false},
		{"test package name in production", "internal/modules/content/application/harness.go", "application_test", false},
		{"external transport harness", "internal/transport/grpc/harness_test.go", "grpc_test", true},
		{"production transport", "internal/transport/grpc/harness.go", "grpc", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			violations := scanClassificationFixture(t, tc.path, "package "+tc.pkg+"\n"+imports)
			if got := len(violations) == 0; got != tc.wantAllowed {
				t.Fatalf("allowed = %v, want %v: %v", got, tc.wantAllowed, violations)
			}
		})
	}
}

func Test_Architecture_ApplicationOwnsOptionsNotSQL(t *testing.T) {
	cases := []struct {
		name, source string
		wantAllowed  bool
	}{
		{"transaction options", `import "database/sql"; var options = sql.TxOptions{Isolation: sql.LevelReadCommitted}`, true},
		{"aliased transaction options", `import stdsql "database/sql"; var options = stdsql.TxOptions{Isolation: stdsql.LevelReadCommitted}`, true},
		{"open database", `import "database/sql"; func f(){ sql.Open("pgx", "dsn") }`, false},
		{"SQL connection type", `import "database/sql"; var db *sql.DB`, false},
		{"dot SQL import", `import . "database/sql"; var options = TxOptions{}`, false},
		{"platform database", `import _ "github.com/PengYuee/SCYG.Blog/backend/internal/platform/database"`, false},
		{"direct SQL", `func f(){ tx.Exec("DELETE FROM articles") }`, false},
		{"raw SQL", `func f(){ tx.Raw("SELECT * FROM articles") }`, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			violations := scanClassificationFixture(t, "internal/modules/content/application/workflow.go", "package application\n"+tc.source)
			if got := len(violations) == 0; got != tc.wantAllowed {
				t.Fatalf("allowed = %v, want %v: %v", got, tc.wantAllowed, violations)
			}
		})
	}
}

func Test_Architecture_ExternalHarnessCannotImportPrivateModules(t *testing.T) {
	path := "internal/transport/grpc/harness_test.go"
	violations := scanClassificationFixture(t, path, `package grpc_test
import _ "github.com/PengYuee/SCYG.Blog/backend/internal/modules/content/internal/private"`)
	if !containsViolation(violations, "ARCH_INTERNAL_IMPORT", path) {
		t.Fatalf("external harness bypassed module privacy: %v", violations)
	}
}

func Test_Architecture_GeneratedMarkerDoesNotExemptImports(t *testing.T) {
	path := "internal/modules/content/application/bindings.go"
	violations := scanClassificationFixture(t, path, `// Code generated by protoc-gen-go. DO NOT EDIT.
package application
import _ "google.golang.org/grpc"`)
	if !containsViolation(violations, "ARCH_FORBIDDEN_IMPORT", path) {
		t.Fatalf("generated marker bypassed production layers: %v", violations)
	}
}

func scanClassificationFixture(t *testing.T, relative, source string) []Violation {
	t.Helper()
	root := t.TempDir()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	violations, err := Scan(root)
	if err != nil {
		t.Fatal(err)
	}
	return violations
}
